export enum Technologies {
    AWSS3 = "AWS S3",
    CSS = "CSS",
    Express = "Express",
    Handlebars = "Handlebars",
    Heroku = "Heroku",
    Node = "Node",
    PostgreSQL = "PostgreSQL",
    HTML = "HTML",
    JavaScript = "JavaScript",
    JQuery = "jQuery",
    React = "React",
    Redux = "Redux",
    SocketIO = "Socket.IO",
    TypeScript = "TypeScript",
    Vue = "Vue",
}
